version: "3"

services:
  next-app:
    container_name: next-app
    build:
      context: ../../
      dockerfile: src/docker/Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE:-http://backend:8080/query}
        PRIVATE_API_URL: ${PRIVATE_API_URL:-http://backend:8080/query}
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network


  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true